language: php

php: 5.6

before_install:
  - composer self-update

install:
  - composer install --no-dev --prefer-dist --optimize-autoloader

script:
  - echo ""

before_deploy:
  - mv app/config/config.local.neon.sample app/config/config.local.neon
  - rm -f app/config/config.ci.local.neon
  - zip -r SRS app backup libs log migrations temp vendor www README.md

deploy:
  provider: releases
  api_key:
    secure: DT6qfSlb6dVuXZKMnPLddyheWDsAargfBD2KfchL3uIy86c7iJBeovXXZxdXQDslDAMfllJqCsTeuX0arfUXLJYwT54aNysBqdrnz9TZcsovcM3E+g8YCWjIrbVMG46wXC2cz8DMrhXhHlg36BzNrEaWIe+ov5gp6EgafWyhK2U=
  file: SRS.zip
  skip_cleanup: true
  on:
    repo: skaut/SRS
    branch: master
    tags: true
